// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tJTP8SXOsUTUAGC92Ap3xx1_bJ_21mw',
    appId: '1:406801092134:web:3e43e8f3d4132180dba0e7',
    messagingSenderId: '406801092134',
    projectId: 'water-bottle-54c78',
    authDomain: 'water-bottle-54c78.firebaseapp.com',
    storageBucket: 'water-bottle-54c78.appspot.com',
    measurementId: 'G-68SQDSE0VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5sU6S6MSH8D2M8n0MKD9icke6uSbmmM',
    appId: '1:406801092134:android:654bc6aa90216efddba0e7',
    messagingSenderId: '406801092134',
    projectId: 'water-bottle-54c78',
    storageBucket: 'water-bottle-54c78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW99ZRnJcIZZFLOHGcdj-axuUB-RZSTm4',
    appId: '1:406801092134:ios:1df3b518762eb149dba0e7',
    messagingSenderId: '406801092134',
    projectId: 'water-bottle-54c78',
    storageBucket: 'water-bottle-54c78.appspot.com',
    iosClientId: '406801092134-padctmd7itlcurfh7nan4k62pt5446iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterBottle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW99ZRnJcIZZFLOHGcdj-axuUB-RZSTm4',
    appId: '1:406801092134:ios:1df3b518762eb149dba0e7',
    messagingSenderId: '406801092134',
    projectId: 'water-bottle-54c78',
    storageBucket: 'water-bottle-54c78.appspot.com',
    iosClientId: '406801092134-padctmd7itlcurfh7nan4k62pt5446iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterBottle',
  );
}
